version: '3'

volumes:
  postgres-data-volume:

networks:
  popoll-bdd-network:

services:
  docker-popoll-config:
    build: ./popoll-config
    image: popoll-config:latest
    restart: always
    ports:
      - "8888:8888"
  docker-popoll-eureka:
    build: ./popoll-eureka
    image: popoll-eureka:latest
    restart: always
    ports:
      - "8000:8000"
  docker-popoll-zuul:
    build: ./popoll-zuul
    image: popoll-zuul:latest
    restart: always
    ports:
      - "8001:8001"
  docker-popoll-survey:
    build: ./popoll-survey
    image: popoll-survey:latest
    restart: always
    networks:
      - popoll-bdd-network
    ports:
      - "8002:8080"
  docker-popoll-slackbot:
    build: ./popoll-slackbot
    image: popoll-slackbot:latest
    restart: always
    ports:
      - "8003:8080"
  docker-popoll-ui:
    build: ./popoll-ui
    image: popoll-ui:latest
    restart: always
    ports:
      - "9090:80"
  docker-popoll-bdd:
    image: postgres:latest
    restart: always
    networks:
      - popoll-bdd-network
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data