spring:
  application:
    name: popoll-slackbot
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

info:
  slack:
    webhook-url: "https://hooks.slack.com/services/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"
    client-id: ""
    client-secret: ""
    verification-token: "xtZSVP1GVN7ewp54Jzs0Mzv6"