# Spring properties
spring:
  application:
     name: popoll-eureka
  thymeleaf:
    enabled: false

# Discovery Server
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.context-path}/health
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true

server:
  port: 8080

management:
  context-path: /monitor